# Scavenger Hunt Photo List

__(You must have at least one team member in each picture)__

- [ ] A tour group
- [ ] A book store
- [ ] A book about Seattle
- [ ] Odd art in the central library
- [ ] The campiest movie you can find at the central library
- [ ] A pet that isn't a dog
- [ ] A burlesque flyer
- [ ] Flyer for a show that happened over a year ago
- [ ] Chihuli glass art
- [ ] A climbing wall
- [ ] A farmer's market
- [ ] A fresh donut
- [ ] A fruit or vegetable that no one in your group has tried before
- [ ] A group of 4+ bikers
- [ ] Someone in Seahawks gear
- [ ] Someone in Sounders gear
- [ ] A fancy mustache
- [ ] A mohawk
- [ ] A terrible parking job
- [ ] An out-of-state license plate
- [ ] The Ferris Wheel
- [ ] A promotional pen from a software company
- [ ] A rainbow
- [ ] A ferry
- [ ] A Henry mural
- [ ] A segway or hoverboard
- [ ] The EMP
- [ ] A stadium
- [ ] A telephone booth
- [ ] A theatre (movie or stage)
- [ ] A very small coffee
- [ ] Air-born fish at pike's place
- [ ] An antiques store
- [ ] As many Seattle pigs as you can find
- [ ] Baby swings (the ones you can't fall out of)
- [ ] Benaroya Hall
- [ ] Food served from a cart or a truck
- [ ] Fran's Chocolates
- [ ] Olympic Sculpture Park
- [ ] The P-I GLobe
- [ ] Freeway park
- [ ] A working pinball or arcade machine
- [ ] Ostentatious recycling
- [ ] People waiting in line at Dick's
- [ ] Put some gum on the gum wall
- [ ] A Seattle-centric tattoo
- [ ] SAM
- [ ] Someone eating seafood
- [ ] Someone using a selfie stick
- [ ] Someone using a Microsoft & an Apple device at the same time
- [ ] A Duck Boat
- [ ] Something magical
- [ ] Something old
- [ ] Something brand new
- [ ] Something that rattles
- [ ] Something wet
- [ ] Something with a tail
- [ ] Something with batteries
- [ ] Teatro ZinZanni
- [ ] The original Starbucks
- [ ] Beecher's Cheese
- [ ] Yoga pants and a briefcase
- [ ] Your entire group in a picture with the Space Needle
